name: tasks
syntax:
  DeadlineDate:
    firstCharacters:
      - "📅"
    regex: "📅\\s*\\d{4}\\-\\d{2}\\-\\d{2}"
    styles:
      backgroundColor: "rgba(22,22,22,0.07)"
  CompletedDate:
    firstCharacters:
      - "✅"
    regex: "✅\\s*\\d{4}\\-\\d{2}\\-\\d{2}"
    styles:
      backgroundColor: "rgba(22,22,22,0.07)"
  RepeatInterval:
    firstCharacters:
      - "🔁"
    regex: "🔁\\s*every\\s+\\w+"
    styles:
      backgroundColor: "rgba(22,22,22,0.07)"
functions:
  # API
  updateTaskState:
    path: task.ts:updateTaskState


  turnIntoTask:
    redirect: template.applyLineReplace
    slashCommand:
      name: task
      description: Turn into task
      match: "^(\\s*)[\\-\\*]?\\s*(\\[[ xX]\\])?\\s*"
      replace: "$1* [ ] "

  indexTasks:
    path: "./task.ts:indexTasks"
    events:
      - page:index
  taskToggle:
    path: "./task.ts:taskToggle"
    events:
      - page:click
  # itemQueryProvider:
  #   path: ./task.ts:queryProvider
  #   events:
  #     - query:task
  taskToggleCommand:
    path: ./task.ts:taskCycleCommand
    command:
      name: "Task: Cycle State"
      key: Alt-t
  taskPostponeCommand:
    path: ./task.ts:postponeCommand
    command:
      name: "Task: Postpone"
      key: Alt-+
      contexts:
        - DeadlineDate
  previewTaskToggle:
    path: ./task.ts:previewTaskToggle
    events:
      - preview:click

  taskComplete:
    path: ./complete.ts:completeTaskState
    events:
    - editor:complete